# Generated by Django 5.2 on 2026-02-24 14:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('company', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Raison sociale')),
                ('address', models.CharField(blank=True, max_length=120, verbose_name='Adresse')),
                ('zipcode', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('city', models.CharField(blank=True, max_length=60, verbose_name='Ville')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('rcs', models.CharField(blank=True, max_length=60, verbose_name='N° RCS')),
                ('siret', models.CharField(blank=True, max_length=20, verbose_name='N° SIRET')),
                ('vat_number', models.CharField(blank=True, max_length=20, verbose_name='N° TVA')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reception_number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='N° réception')),
                ('delivery_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date de livraison')),
                ('invoice_number', models.CharField(blank=True, max_length=60, verbose_name='N° facture')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptions', to='company.company')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchasing.supplier', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Réception',
                'verbose_name_plural': 'Réceptions',
                'ordering': ['-delivery_date'],
            },
        ),
        migrations.CreateModel(
            name='SupplierContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=60, verbose_name='Nom')),
                ('job_title', models.CharField(blank=True, max_length=60, verbose_name='Fonction')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='Mobile')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='purchasing.supplier')),
            ],
            options={
                'verbose_name': 'Contact fournisseur',
                'verbose_name_plural': 'Contacts fournisseurs',
            },
        ),
        migrations.CreateModel(
            name='SupplierIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_item_number', models.CharField(blank=True, max_length=40, verbose_name='Référence fournisseur')),
                ('supplier_item_name', models.CharField(blank=True, max_length=100, verbose_name='Désignation fournisseur')),
                ('ean13', models.CharField(blank=True, max_length=13, verbose_name='EAN13')),
                ('negotiated_price', models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='Prix négocié HT')),
                ('is_preferred', models.BooleanField(default=False, verbose_name='Fournisseur préféré')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_refs', to='catalog.ingredient')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_ingredients', to='purchasing.supplier')),
            ],
            options={
                'verbose_name': 'Référence fournisseur',
                'verbose_name_plural': 'Références fournisseurs',
            },
        ),
        migrations.CreateModel(
            name='ReceptionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracability_number', models.CharField(blank=True, max_length=60, verbose_name='N° de lot')),
                ('best_before', models.DateField(blank=True, null=True, verbose_name='DLC / DLUO')),
                ('invoiced_quantity', models.DecimalField(decimal_places=3, max_digits=9, verbose_name='Quantité facturée')),
                ('invoiced_price', models.DecimalField(decimal_places=4, max_digits=9, verbose_name='Prix unitaire HT')),
                ('invoiced_amount', models.DecimalField(decimal_places=3, editable=False, max_digits=10, verbose_name='Montant HT')),
                ('batch_on_site', models.BooleanField(default=True, verbose_name='Lot présent')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.ingredient', verbose_name='Ingrédient')),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.reception')),
                ('supplier_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchasing.supplieringredient', verbose_name='Référence fournisseur')),
            ],
            options={
                'verbose_name': 'Ligne de réception',
                'verbose_name_plural': 'Lignes de réception',
            },
        ),
        migrations.CreateModel(
            name='CompanyIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_reference', models.CharField(blank=True, max_length=20, verbose_name='Emplacement')),
                ('minimum_stock', models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='Stock minimum')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_configs', to='company.company')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_configs', to='catalog.ingredient')),
                ('storage_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.storageplace', verbose_name='Lieu de stockage')),
            ],
            options={
                'verbose_name': 'Configuration ingrédient / site',
                'verbose_name_plural': 'Configurations ingrédients / sites',
                'constraints': [models.UniqueConstraint(fields=('company', 'ingredient'), name='unique_company_ingredient')],
            },
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_supplier_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='supplieringredient',
            constraint=models.UniqueConstraint(fields=('supplier', 'ingredient'), name='unique_supplier_ingredient'),
        ),
    ]
