# Generated by Django 5.2 on 2026-03-03 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_recipe_yield_rate'),
        ('purchasing', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='purchasing/documents/', verbose_name='Document')),
                ('document_type', models.CharField(choices=[('bl', 'Bon de livraison'), ('invoice', 'Facture'), ('other', 'Autre document')], default='other', max_length=10, verbose_name='Type')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='Date du document')),
                ('reference', models.CharField(blank=True, max_length=60, verbose_name='N° BL / Facture')),
                ('status', models.CharField(choices=[('pending', 'En attente de traitement'), ('parsing', 'OCR en cours...'), ('parsed', 'Analysé — en attente de validation'), ('validated', 'Validé — prix appliqués'), ('error', 'Erreur OCR')], default='pending', max_length=10)),
                ('ocr_raw', models.JSONField(blank=True, default=dict, verbose_name='Résultat OCR brut')),
                ('ocr_engine', models.CharField(blank=True, max_length=20, verbose_name='Moteur OCR utilisé')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='purchasing.supplier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_documents', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Document de livraison',
                'verbose_name_plural': 'Documents de livraison',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('product', 'Produit'), ('sector_tax', 'Taxe filière'), ('discount', 'Remise'), ('shipping', 'Frais de port'), ('other', 'Autre')], default='product', max_length=12)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('raw_label', models.CharField(max_length=300, verbose_name='Libellé brut OCR')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('unit_price_ht', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='PU HT')),
                ('total_ht', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total HT')),
                ('match_score', models.FloatField(blank=True, null=True, verbose_name='Score matching (0-100)')),
                ('match_confirmed', models.BooleanField(default=False, verbose_name='Matching confirmé')),
                ('tax_code', models.CharField(blank=True, max_length=20, verbose_name='Code taxe')),
                ('applied', models.BooleanField(default=False, verbose_name='Prix appliqué')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.deliverydocument')),
                ('matched_ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_lines', to='catalog.ingredient', verbose_name='Ingrédient associé')),
                ('reception_line', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_line', to='purchasing.receptionline')),
            ],
            options={
                'verbose_name': 'Ligne document',
                'verbose_name_plural': 'Lignes document',
                'ordering': ['order'],
            },
        ),
    ]
