# Generated by Django 5.2 on 2026-03-03 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_recipe_yield_rate'),
        ('purchasing', '0002_deliverydocument_deliveryline'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierLabelMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_label', models.CharField(max_length=300, verbose_name='Libellé brut')),
                ('normalized_label', models.CharField(max_length=300, verbose_name='Libellé normalisé')),
                ('score', models.PositiveSmallIntegerField(default=1, verbose_name='Score confiance')),
                ('last_seen', models.DateField(auto_now=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.ingredient')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchasing.supplier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Mapping libellé fournisseur',
                'ordering': ['-score'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'supplier', 'normalized_label'), name='unique_supplier_label_mapping')],
            },
        ),
    ]
