# Generated by Django 5.2 on 2026-02-24 14:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('company', '0001_initial'),
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date de production')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_batches', to='company.company')),
            ],
            options={
                'verbose_name': 'Lot de production',
                'verbose_name_plural': 'Lots de production',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantité produite')),
                ('best_before', models.DateField(blank=True, null=True, verbose_name='DLC / DLUO')),
                ('opening_date', models.DateField(blank=True, null=True, verbose_name="Date d'ouverture")),
                ('in_stock', models.BooleanField(default=True, verbose_name='En stock')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='production.productionbatch')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.recipe', verbose_name='Recette')),
            ],
            options={
                'verbose_name': 'Enregistrement de production',
                'verbose_name_plural': 'Enregistrements de production',
            },
        ),
        migrations.CreateModel(
            name='Traceability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Quantité utilisée')),
                ('production_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traceability_lines', to='production.productionrecord')),
                ('reception_line', models.ForeignKey(limit_choices_to={'batch_on_site': True}, on_delete=django.db.models.deletion.PROTECT, to='purchasing.receptionline', verbose_name='Lot reçu utilisé')),
            ],
            options={
                'verbose_name': 'Traçabilité',
                'verbose_name_plural': 'Traçabilités',
            },
        ),
    ]
