# Generated by Django 5.2 on 2026-02-24 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Importé le')),
                ('import_format', models.CharField(choices=[('csv', 'CSV générique'), ('zelty', 'Zelty'), ('lightspeed', 'Lightspeed'), ('sumup', 'SumUp'), ('other', 'Autre')], default='csv', max_length=20, verbose_name='Format')),
                ('source_file', models.FileField(upload_to='sales/imports/', verbose_name='Fichier source')),
                ('period_start', models.DateField(verbose_name='Début de période')),
                ('period_end', models.DateField(verbose_name='Fin de période')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Traité')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_imports', to='company.company')),
            ],
            options={
                'verbose_name': 'Import CA',
                'verbose_name_plural': 'Imports CA',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date prévue')),
                ('forecasted_revenue', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='CA prévu TTC')),
                ('actual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='CA réel TTC')),
                ('method', models.CharField(choices=[('linear', 'Régression linéaire'), ('moving_avg', 'Moyenne mobile'), ('seasonal', 'Saisonnalité N-1')], default='seasonal', max_length=20, verbose_name='Méthode')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Généré le')),
                ('week_number', models.PositiveSmallIntegerField(verbose_name='Numéro de semaine')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Année')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='company.company')),
            ],
            options={
                'verbose_name': 'Prévision CA',
                'verbose_name_plural': 'Prévisions CA',
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('company', 'date', 'method'), name='unique_forecast_per_day_per_method')],
            },
        ),
        migrations.CreateModel(
            name='DailySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('revenue_ttc', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='CA TTC')),
                ('revenue_ht', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='CA HT')),
                ('covers', models.PositiveIntegerField(default=0, verbose_name='Nombre de couverts / tickets')),
                ('is_closed', models.BooleanField(default=False, help_text='Une journée clôturée ne peut plus être modifiée', verbose_name='Journée clôturée')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sales', to='company.company')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salesimport', verbose_name="Source d'import")),
            ],
            options={
                'verbose_name': 'CA journalier',
                'verbose_name_plural': 'CA journaliers',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('company', 'date'), name='unique_daily_sales_per_company')],
            },
        ),
    ]
