# Generated by Django 5.2 on 2026-02-27 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0007_alter_recipecategory_options_and_more'),
        ('tenants', '0001_initial'),
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('purchase', 'Achat fournisseur'), ('retail', 'Vente détail'), ('wholesale', 'Vente en gros')], max_length=20, verbose_name='Canal')),
                ('price_ht', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Prix HT (€)')),
                ('price_ttc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix TTC (€)')),
                ('valid_from', models.DateField(verbose_name='Valide à partir du')),
                ('valid_until', models.DateField(blank=True, help_text='Laisser vide = prix courant actif', null=True, verbose_name="Valide jusqu'au")),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_records', to='catalog.ingredient', verbose_name='Ingrédient')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_records', to='catalog.recipe', verbose_name='Recette')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_records', to='tenants.tenant')),
                ('vat_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='utilities.vatrate', verbose_name='Taux de TVA')),
            ],
            options={
                'verbose_name': 'Enregistrement de prix',
                'verbose_name_plural': 'Enregistrements de prix',
                'ordering': ['-valid_from'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('ingredient__isnull', False), ('recipe__isnull', True)), models.Q(('ingredient__isnull', True), ('recipe__isnull', False)), _connector='OR'), name='pricerecord_ingredient_xor_recipe', violation_error_message='Un PriceRecord doit être lié à un ingrédient OU une recette, pas les deux.'), models.CheckConstraint(condition=models.Q(models.Q(('channel', 'purchase'), _negated=True), ('ingredient__isnull', False), _connector='OR'), name='pricerecord_purchase_only_for_ingredient', violation_error_message="Le canal 'purchase' est réservé aux ingrédients.")],
            },
        ),
    ]
