# Generated by Django 5.2 on 2026-02-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricerecord',
            name='source',
            field=models.CharField(choices=[('manual', 'Saisie manuelle'), ('ocr_bl', 'OCR bon de livraison'), ('ocr_invoice', 'OCR facture'), ('import', 'Import fichier')], default='manual', max_length=20, verbose_name='Source'),
        ),
    ]
