# Generated by Django 5.2 on 2026-02-24 16:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_recipeequipment'),
        ('company', '0002_equipment'),
        ('pms', '0001_initial'),
        ('production', '0001_initial'),
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Début inventaire')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validé le')),
                ('status', models.CharField(choices=[('draft', 'En cours'), ('validated', 'Validé')], default='draft', max_length=10, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='company.company')),
            ],
            options={
                'verbose_name': 'Inventaire',
                'verbose_name_plural': 'Inventaires',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=10, verbose_name='Unité')),
                ('theoretical_quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantité théorique (stock calculé)')),
                ('counted_quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantité comptée')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Notes')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.ingredient', verbose_name='Ingrédient')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='stock.inventory')),
            ],
            options={
                'verbose_name': "Ligne d'inventaire",
                'verbose_name_plural': "Lignes d'inventaire",
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Quantité en stock')),
                ('unit', models.CharField(max_length=10, verbose_name='Unité')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='company.company')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='catalog.ingredient')),
            ],
            options={
                'verbose_name': 'Niveau de stock',
                'verbose_name_plural': 'Niveaux de stock',
                'ordering': ['ingredient__name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('reception', 'Réception fournisseur'), ('production', 'Consommation production'), ('production_in', 'Entrée production (produit fini)'), ('correction', 'Correction manuelle'), ('transfer_out', 'Transfert sortant'), ('transfer_in', 'Transfert entrant'), ('inventory', 'Correction inventaire')], max_length=20, verbose_name='Type')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Positif = entrée, Négatif = sortie', max_digits=10, verbose_name='Quantité')),
                ('unit', models.CharField(max_length=10, verbose_name='Unité')),
                ('moved_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date / heure')),
                ('correction_reason', models.CharField(blank=True, choices=[('waste', 'Perte / jet'), ('expired', 'Périmé'), ('damaged', 'Abîmé / cassé'), ('gift', 'Don'), ('theft', 'Vol'), ('other', 'Autre')], max_length=20, verbose_name='Raison de correction')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='company.company')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='catalog.ingredient')),
                ('inventory_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='stock.inventoryline')),
                ('production_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='production.productionrecord')),
                ('reception_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='purchasing.receptionline')),
                ('transfer_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='pms.internaltransferline')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-moved_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='inventoryline',
            constraint=models.UniqueConstraint(fields=('inventory', 'ingredient'), name='unique_ingredient_per_inventory'),
        ),
        migrations.AddConstraint(
            model_name='stocklevel',
            constraint=models.UniqueConstraint(fields=('company', 'ingredient'), name='unique_stock_level_per_company_ingredient'),
        ),
    ]
