# Generated by Django 5.2 on 2026-02-24 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CiqualIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciqual_code', models.CharField(max_length=20, unique=True, verbose_name='Code CIQUAL')),
                ('name_fr', models.CharField(max_length=200, verbose_name='Nom français')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Nom anglais')),
                ('group', models.CharField(blank=True, max_length=100, verbose_name='Groupe CIQUAL')),
                ('sub_group', models.CharField(blank=True, max_length=100, verbose_name='Sous-groupe CIQUAL')),
                ('energy_kj', models.FloatField(blank=True, null=True, verbose_name='Énergie (kJ/100g)')),
                ('energy_kcal', models.FloatField(blank=True, null=True, verbose_name='Énergie (kcal/100g)')),
                ('water', models.FloatField(blank=True, null=True, verbose_name='Eau (g/100g)')),
                ('protein', models.FloatField(blank=True, null=True, verbose_name='Protéines (g/100g)')),
                ('carbohydrates', models.FloatField(blank=True, null=True, verbose_name='Glucides (g/100g)')),
                ('sugars', models.FloatField(blank=True, null=True, verbose_name='Dont sucres (g/100g)')),
                ('fat', models.FloatField(blank=True, null=True, verbose_name='Lipides (g/100g)')),
                ('saturates', models.FloatField(blank=True, null=True, verbose_name='Dont saturés (g/100g)')),
                ('fiber', models.FloatField(blank=True, null=True, verbose_name='Fibres (g/100g)')),
                ('salt', models.FloatField(blank=True, null=True, verbose_name='Sel (g/100g)')),
                ('sodium', models.FloatField(blank=True, null=True, verbose_name='Sodium (mg/100g)')),
                ('calcium', models.FloatField(blank=True, null=True, verbose_name='Calcium (mg/100g)')),
                ('iron', models.FloatField(blank=True, null=True, verbose_name='Fer (mg/100g)')),
                ('vitamin_c', models.FloatField(blank=True, null=True, verbose_name='Vitamine C (mg/100g)')),
                ('vitamin_d', models.FloatField(blank=True, null=True, verbose_name='Vitamine D (µg/100g)')),
            ],
            options={
                'verbose_name': 'Ingrédient CIQUAL',
                'verbose_name_plural': 'Ingrédients CIQUAL',
                'ordering': ['name_fr'],
            },
        ),
        migrations.CreateModel(
            name='TenantCiqualMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name_lower', models.CharField(help_text='Nom en minuscules, sans accents — clé de recherche', max_length=200, verbose_name='Nom ingrédient normalisé')),
                ('score', models.PositiveIntegerField(default=1, help_text='Incrémenté à chaque confirmation — utilisé pour le tri', verbose_name="Score d'apprentissage")),
                ('last_used', models.DateTimeField(auto_now=True, verbose_name='Dernière utilisation')),
                ('ciqual_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciqual.ciqualingredient', verbose_name='Entrée CIQUAL associée')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciqual_mappings', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Mapping CIQUAL (apprentissage)',
                'verbose_name_plural': 'Mappings CIQUAL (apprentissage)',
                'ordering': ['-score', '-last_used'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'ingredient_name_lower', 'ciqual_ingredient'), name='unique_tenant_ciqual_mapping')],
            },
        ),
    ]
