# Generated by Django 5.2 on 2026-02-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Allergène')),
            ],
            options={
                'verbose_name': 'Allergène',
                'verbose_name_plural': 'Allergènes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Unité')),
                ('unit_type', models.CharField(choices=[('weight', 'Poids'), ('volume', 'Volume'), ('piece', 'Pièce/Conditionnement')], max_length=20, verbose_name='Type')),
                ('symbol', models.CharField(max_length=10, verbose_name='Symbole')),
            ],
            options={
                'verbose_name': 'Unité',
                'verbose_name_plural': 'Unités',
                'ordering': ['unit_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VatRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Libellé')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Taux')),
            ],
            options={
                'verbose_name': 'Taux de TVA',
                'verbose_name_plural': 'Taux de TVA',
                'ordering': ['rate'],
            },
        ),
    ]
