# Generated by Django 5.2 on 2026-03-04 09:14

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0011_recipe_yield_rate'),
        ('purchasing', '0003_supplierlabelmapping'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarcassTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du gabarit')),
                ('species', models.CharField(choices=[('beef', 'Bœuf'), ('veal', 'Veau'), ('lamb', 'Agneau'), ('pork', 'Porc'), ('poultry', 'Volaille'), ('other', 'Autre')], max_length=20, verbose_name='Espèce')),
                ('purchase_unit', models.CharField(blank=True, help_text='Ex: demi-carcasse, quartier arrière, poulet entier', max_length=100, verbose_name="Unité d'achat")),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carcass_templates', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Gabarit de démontage',
                'ordering': ['species', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ButcherySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Ex: Demi-bœuf Charolaise n°47 — SCA Le Pré Vert', max_length=200, verbose_name='Description')),
                ('species', models.CharField(choices=[('beef', 'Bœuf'), ('veal', 'Veau'), ('lamb', 'Agneau'), ('pork', 'Porc'), ('poultry', 'Volaille'), ('other', 'Autre')], max_length=20, verbose_name='Espèce')),
                ('session_date', models.DateField(verbose_name='Date de découpe')),
                ('status', models.CharField(choices=[('open', 'En cours'), ('completed', 'Terminée — en attente de calcul'), ('validated', 'Validée — prix calculés')], default='open', max_length=20)),
                ('purchase_weight_kg', models.DecimalField(decimal_places=3, max_digits=8, verbose_name="Poids à l'achat (kg)")),
                ('purchase_price_per_kg', models.DecimalField(decimal_places=4, max_digits=8, verbose_name="Prix d'achat (€/kg HT)")),
                ('purchase_total_ht', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coût achat total HT (€)')),
                ('sector_tax_total_ht', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Taxes filière HT (€)')),
                ('processing_cost_ht', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Désossage, mise sous vide, etc.', max_digits=8, verbose_name='Prestation externe HT (€)')),
                ('total_output_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Poids total valorisé (kg)')),
                ('total_waste_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Poids pertes/déchets (kg)')),
                ('real_yield_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Rendement réel (%)')),
                ('avg_cost_per_kg', models.DecimalField(blank=True, decimal_places=4, help_text='Coût total / poids valorisé — info comparative', max_digits=8, null=True, verbose_name='Coût moyen brut (€/kg valorisé)')),
                ('global_margin_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Taux de marge global réalisé')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('butcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Boucher')),
                ('delivery_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='butchery_sessions', to='purchasing.deliveryline', verbose_name="Ligne BL d'achat")),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='butchery_sessions', to='tenants.tenant')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='butchery.carcasstemplate', verbose_name='Gabarit utilisé')),
            ],
            options={
                'verbose_name': 'Session de découpe',
                'ordering': ['-session_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarcassTemplateLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la pièce')),
                ('norm_code', models.CharField(blank=True, help_text='Ex: code INTERBEV', max_length=20, verbose_name='Code nomenclature')),
                ('output_type', models.CharField(choices=[('ingredient', 'Ingrédient catalogue'), ('sellable', 'Vente directe'), ('byproduct', 'Sous-produit valorisable'), ('waste', 'Déchet / perte')], default='ingredient', max_length=20, verbose_name='Destination')),
                ('selling_price_ttc', models.DecimalField(blank=True, decimal_places=2, help_text='Prix de vente TTC au kg — sert au calcul du prix de revient', max_digits=8, null=True, verbose_name='PV TTC de référence (€/kg)')),
                ('vat_rate', models.DecimalField(decimal_places=4, default=Decimal('0.055'), help_text='Ex: 0.055 pour 5.5%', max_digits=5, verbose_name='Taux TVA')),
                ('expected_yield_pct', models.DecimalField(blank=True, decimal_places=2, help_text='% du poids de la pièce parente attendu', max_digits=6, null=True, verbose_name='Rendement théorique (%)')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('linked_ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_lines', to='catalog.ingredient', verbose_name='Ingrédient lié')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='butchery.carcasstemplateline', verbose_name='Pièce parente')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='butchery.carcasstemplate')),
            ],
            options={
                'verbose_name': 'Ligne gabarit',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ButcheryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la pièce')),
                ('output_type', models.CharField(choices=[('ingredient', 'Ingrédient catalogue'), ('sellable', 'Vente directe'), ('byproduct', 'Sous-produit valorisable'), ('waste', 'Déchet / perte'), ('processing', 'En cours de découpe')], default='ingredient', max_length=20, verbose_name='Destination')),
                ('real_weight_kg', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Poids réel (kg)')),
                ('selling_price_ttc', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='PV TTC (€/kg)')),
                ('vat_rate', models.DecimalField(decimal_places=4, default=Decimal('0.055'), max_digits=5, verbose_name='Taux TVA')),
                ('cost_per_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Prix de revient (€/kg)')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coût total (€)')),
                ('theoretical_ca', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='CA théorique (€)')),
                ('byproduct_selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='PV sous-produit (€/kg)')),
                ('byproduct_sold', models.BooleanField(default=False, verbose_name='Sous-produit vendu')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Pesée confirmée')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='butchery_lines', to='catalog.ingredient', verbose_name='Ingrédient lié')),
                ('parent_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_lines', to='butchery.butcheryline', verbose_name='Pièce parente')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='butchery.butcherysession')),
                ('template_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='butchery.carcasstemplateline', verbose_name='Ligne gabarit')),
            ],
            options={
                'verbose_name': 'Ligne de découpe',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='YieldRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('purchase_weight_kg', models.DecimalField(decimal_places=3, max_digits=8)),
                ('purchase_price_per_kg', models.DecimalField(decimal_places=4, max_digits=8)),
                ('total_cost_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('global_yield_pct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('waste_pct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('effective_cost_per_kg', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Coût réel/kg valorisé')),
                ('global_margin_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('yields_data', models.JSONField(default=dict, help_text='Détail rendements par pièce')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yield_record', to='butchery.butcherysession')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchasing.supplier')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='butchery.carcasstemplate')),
            ],
            options={
                'verbose_name': 'Historique rendement',
                'ordering': ['-session_date'],
            },
        ),
    ]
