# Generated by Django 5.2 on 2026-02-24 14:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('company', '0001_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Localisation')),
                ('cleaning_product', models.CharField(blank=True, max_length=100, verbose_name='Produit nettoyant')),
                ('disinfection_product', models.CharField(blank=True, max_length=100, verbose_name='Produit désinfectant')),
                ('procedure', models.TextField(blank=True, verbose_name='Procédure')),
                ('reference_document', models.CharField(blank=True, help_text='Réservé pour future intégration RAG/bibliothèque PMS', max_length=200, verbose_name='Référence document PMS')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_zones', to='company.company')),
            ],
            options={
                'verbose_name': 'Zone / Surface à nettoyer',
                'verbose_name_plural': 'Zones / Surfaces à nettoyer',
                'ordering': ['company', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CleaningSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('after_use', 'Après chaque utilisation'), ('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('biweekly', 'Bihebdomadaire'), ('monthly', 'Mensuel'), ('annual', 'Annuel')], max_length=20, verbose_name='Fréquence')),
                ('weekday', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], null=True, verbose_name='Jour de la semaine')),
                ('week_parity', models.CharField(blank=True, choices=[('odd', 'Semaines impaires'), ('even', 'Semaines paires')], max_length=4, null=True, verbose_name='Parité semaine')),
                ('week_of_month', models.PositiveSmallIntegerField(blank=True, help_text='Ex: 2 pour la 2ème semaine du mois', null=True, verbose_name='Semaine du mois (1-4)')),
                ('week_of_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Semaine de l'année (1-52)")),
                ('time_slot_label', models.CharField(blank=True, help_text='Ex: Avant ouverture, Pause repas, Après fermeture', max_length=60, verbose_name='Libellé créneau')),
                ('time_slot_order', models.PositiveSmallIntegerField(default=1, help_text='Pour trier les créneaux dans la journée', verbose_name='Ordre du créneau')),
                ('time_slot_hour', models.TimeField(blank=True, help_text='Si vide, utiliser le libellé créneau', null=True, verbose_name='Heure fixe')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='pms.cleaningzone')),
            ],
            options={
                'verbose_name': 'Planning de nettoyage',
                'verbose_name_plural': 'Plannings de nettoyage',
                'ordering': ['zone', 'time_slot_order'],
            },
        ),
        migrations.CreateModel(
            name='CleaningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Effectué le')),
                ('is_compliant', models.BooleanField(default=True, verbose_name='Conforme')),
                ('anomaly_and_action', models.TextField(blank=True, verbose_name='Anomalie constatée & action corrective')),
                ('signed_by_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cleaning_records', to='company.employee', verbose_name='Employé')),
                ('signed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cleaning_records', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pms.cleaningschedule', verbose_name='Planning associé')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='pms.cleaningzone')),
            ],
            options={
                'verbose_name': 'Enregistrement nettoyage',
                'verbose_name_plural': 'Enregistrements nettoyage',
                'ordering': ['-done_at'],
            },
        ),
        migrations.CreateModel(
            name='CookingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_temp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='T° cible (°C)')),
                ('measured_temp', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='T° mesurée (°C)')),
                ('cooking_duration_minutes', models.PositiveIntegerField(blank=True, help_text='Pour les cuissons longues : couple temps/température', null=True, verbose_name='Durée de cuisson (min)')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Relevé le')),
                ('is_compliant', models.BooleanField(default=True, verbose_name='Conforme')),
                ('anomaly_and_action', models.TextField(blank=True, verbose_name='Anomalie & action corrective')),
                ('production_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooking_logs', to='production.productionrecord', verbose_name='Production associée')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.recipe', verbose_name='Recette / Article')),
                ('signed_by_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cooking_logs', to='company.employee')),
                ('signed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cooking_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relevé de cuisson',
                'verbose_name_plural': 'Relevés de cuisson',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='CoolingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_temp', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='T° en entrée cellule (°C)')),
                ('end_temp', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='T° en sortie cellule (°C)')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Durée (min)')),
                ('target_end_temp', models.DecimalField(decimal_places=2, default=3, max_digits=5, verbose_name='T° cible en sortie (°C)')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Relevé le')),
                ('is_compliant', models.BooleanField(default=True, verbose_name='Conforme')),
                ('anomaly_and_action', models.TextField(blank=True, verbose_name='Anomalie & action corrective')),
                ('production_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooling_logs', to='production.productionrecord', verbose_name='Production associée')),
                ('signed_by_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cooling_logs', to='company.employee')),
                ('signed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cooling_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enregistrement refroidissement',
                'verbose_name_plural': 'Enregistrements refroidissement',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='InternalTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date / heure départ')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Date / heure réception')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('from_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='company.company', verbose_name='Site expéditeur')),
                ('received_by_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_transfers', to='company.employee')),
                ('received_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_transfers', to=settings.AUTH_USER_MODEL)),
                ('sent_by_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_transfers', to='company.employee')),
                ('sent_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_transfers', to=settings.AUTH_USER_MODEL)),
                ('to_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='company.company', verbose_name='Site destinataire')),
            ],
            options={
                'verbose_name': 'Transfert interne',
                'verbose_name_plural': 'Transferts internes',
                'ordering': ['-transferred_at'],
            },
        ),
        migrations.CreateModel(
            name='InternalTransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Quantité')),
                ('unit', models.CharField(max_length=10, verbose_name='Unité')),
                ('temp_at_departure', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='T° au départ (°C)')),
                ('temp_at_arrival', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="T° à l'arrivée (°C)")),
                ('temp_max_transport', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='T° maximale transport (°C)')),
                ('is_compliant', models.BooleanField(default=True, verbose_name='Conforme')),
                ('anomaly_and_action', models.TextField(blank=True, verbose_name='Anomalie & action corrective')),
                ('production_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.productionrecord', verbose_name='Lot de production transféré')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pms.internaltransfer')),
            ],
            options={
                'verbose_name': 'Ligne de transfert',
                'verbose_name_plural': 'Lignes de transfert',
            },
        ),
        migrations.CreateModel(
            name='StorageUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('unit_type', models.CharField(choices=[('fridge', 'Réfrigérateur'), ('freezer', 'Congélateur'), ('cold_room', 'Chambre froide positive'), ('frozen_room', 'Chambre froide négative'), ('display', 'Vitrine réfrigérée')], max_length=20, verbose_name='Type')),
                ('temp_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='T° minimale (°C)')),
                ('temp_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='T° maximale (°C)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_units', to='company.company')),
            ],
            options={
                'verbose_name': 'Enceinte froide',
                'verbose_name_plural': 'Enceintes froides',
                'ordering': ['company', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TemperatureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Relevé le')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Température (°C)')),
                ('is_compliant', models.BooleanField(default=True, verbose_name='Conforme')),
                ('anomaly_and_action', models.TextField(blank=True, verbose_name='Anomalie & action corrective')),
                ('signed_by_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='temperature_logs', to='company.employee')),
                ('signed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='temperature_logs', to=settings.AUTH_USER_MODEL)),
                ('storage_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='pms.storageunit')),
            ],
            options={
                'verbose_name': 'Relevé de température',
                'verbose_name_plural': 'Relevés de température',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ThawingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Produit décongelé')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Quantité')),
                ('unit', models.CharField(max_length=10, verbose_name='Unité')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Heure de sortie du congélateur')),
                ('method', models.CharField(choices=[('immediate_cooking', 'Cuisson immédiate'), ('fridge_24h', 'Décongélation au réfrigérateur (24h)'), ('fridge_48h', 'Décongélation au réfrigérateur (48h)'), ('other', 'Autre méthode')], max_length=30, verbose_name='Méthode')),
                ('other_method_description', models.CharField(blank=True, max_length=200, verbose_name='Autre méthode (préciser)')),
                ('anomaly_and_action', models.TextField(blank=True, verbose_name='Anomalie & action corrective')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thawing_logs', to='company.company')),
                ('signed_by_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thawing_logs', to='company.employee')),
                ('signed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thawing_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enregistrement décongélation',
                'verbose_name_plural': 'Enregistrements décongélation',
                'ordering': ['-started_at'],
            },
        ),
    ]
