# Generated by Django 5.2 on 2026-02-24 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Raison sociale')),
                ('company_type', models.CharField(choices=[('REST', 'Restaurant'), ('BAKE', 'Boulangerie'), ('BUTCH', 'Boucherie'), ('FISH', 'Poissonnerie'), ('GROC', 'Épicerie'), ('OTHER', 'Autre')], default='REST', max_length=5, verbose_name='Type')),
                ('address', models.CharField(blank=True, max_length=120, verbose_name='Adresse')),
                ('zipcode', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('city', models.CharField(blank=True, max_length=60, verbose_name='Ville')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('siret', models.CharField(blank=True, max_length=20, verbose_name='SIRET')),
                ('vat_number', models.CharField(blank=True, max_length=20, verbose_name='N° TVA')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Site / Entreprise',
                'verbose_name_plural': 'Sites / Entreprises',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=60, verbose_name='Nom')),
                ('job_title', models.CharField(blank=True, max_length=60, verbose_name='Fonction')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('hourly_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Coût horaire')),
                ('weekly_hours', models.DecimalField(decimal_places=2, default=35, max_digits=5, verbose_name='Heures hebdo')),
                ('is_active', models.BooleanField(default=True, verbose_name='En activité')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='company.company')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='StoragePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nom')),
                ('temperature', models.CharField(choices=[('frozen', 'Surgelé < -18°C'), ('cold_1', 'Réfrigéré 0-2°C'), ('cold_2', 'Réfrigéré 0-4°C'), ('cold_3', 'Frais 4-12°C'), ('dry', 'Sec 15-20°C')], max_length=10, verbose_name='Température')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_places', to='company.company')),
            ],
            options={
                'verbose_name': 'Lieu de stockage',
                'verbose_name_plural': 'Lieux de stockage',
                'ordering': ['company', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(condition=models.Q(('siret__gt', '')), fields=('tenant', 'siret'), name='unique_siret_per_tenant'),
        ),
    ]
