# Generated by Django 5.2 on 2026-02-24 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('capacity', models.DecimalField(decimal_places=3, help_text='Ex: 20 pour un pétrin de 20kg, 24 pour un moule de 24 madeleines', max_digits=8, verbose_name='Capacité par cycle')),
                ('capacity_unit', models.CharField(choices=[('kg', 'kg'), ('litre', 'litre'), ('piece', 'Pièce')], max_length=6, verbose_name='Unité de capacité')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='company.company')),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
                'ordering': ['company', 'name'],
            },
        ),
    ]
