# Generated by Django 5.2 on 2026-02-25 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_equipment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCompanyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Patron / Gérant'), ('production', 'Chef de production'), ('worker', 'Ouvrier / Employé'), ('cleaning', "Agent d'entretien"), ('admin', 'Administrateur')], max_length=20, verbose_name='Rôle')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='company.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rôle utilisateur / site',
                'verbose_name_plural': 'Rôles utilisateurs / sites',
                'ordering': ['company', 'role'],
                'constraints': [models.UniqueConstraint(fields=('user', 'company', 'role'), name='unique_user_company_role')],
            },
        ),
    ]
