# Generated by Django 5.2 on 2026-02-24 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_recipeequipment'),
        ('company', '0002_equipment'),
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du plan')),
                ('planned_date', models.DateField(verbose_name='Date de production prévue')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('validated', 'Validé'), ('done', 'Réalisé'), ('cancelled', 'Annulé')], default='draft', max_length=10, verbose_name='Statut')),
                ('use_forecast', models.BooleanField(default=False, help_text='Si activé, les quantités sont suggérées depuis SalesForecast', verbose_name='Basé sur prévisions CA')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_plans', to='company.company')),
            ],
            options={
                'verbose_name': 'Plan de production',
                'verbose_name_plural': 'Plans de production',
                'ordering': ['-planned_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('received', 'Reçu')], default='draft', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='planning.productionplan')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchasing.supplier', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Bon de commande',
                'verbose_name_plural': 'Bons de commande',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantité')),
                ('unit', models.CharField(max_length=10, verbose_name='Unité')),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='Prix unitaire HT')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Notes')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.ingredient', verbose_name='Ingrédient')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='planning.purchaseorder')),
                ('supplier_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchasing.supplieringredient', verbose_name='Référence fournisseur')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
        migrations.CreateModel(
            name='IngredientNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantité requise')),
                ('available_stock', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Stock disponible')),
                ('to_order', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantité à commander')),
                ('unit', models.CharField(max_length=10, verbose_name='Unité')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.ingredient', verbose_name='Ingrédient')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_needs', to='planning.productionplan')),
            ],
            options={
                'verbose_name': 'Besoin en ingrédient',
                'verbose_name_plural': 'Besoins en ingrédients',
                'ordering': ['ingredient__name'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'ingredient'), name='unique_ingredient_need_per_plan')],
            },
        ),
        migrations.CreateModel(
            name='ProductionPlanLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantité prévue')),
                ('unit', models.CharField(max_length=10, verbose_name='Unité')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Notes')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='planning.productionplan')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.recipe', verbose_name='Recette')),
            ],
            options={
                'verbose_name': 'Ligne de plan',
                'verbose_name_plural': 'Lignes de plan',
                'constraints': [models.UniqueConstraint(fields=('plan', 'recipe'), name='unique_recipe_per_plan')],
            },
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('plan', 'supplier'), name='unique_order_per_plan_supplier'),
        ),
    ]
