# Generated by Django 5.2 on 2026-02-24 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nom')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_categories', to='tenants.tenant')),
            ],
            options={
                'verbose_name': "Catégorie d'ingrédient",
                'verbose_name_plural': "Catégories d'ingrédients",
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('composition', models.TextField(blank=True, verbose_name='Composition / étiquette')),
                ('purchase_unit', models.CharField(choices=[('kg', 'kg'), ('litre', 'litre'), ('pièce', 'pièce'), ('paquet', 'paquet'), ('colis', 'colis')], max_length=10, verbose_name="Unité d'achat")),
                ('use_unit', models.CharField(choices=[('kg', 'kg'), ('litre', 'litre'), ('pièce', 'pièce'), ('paquet', 'paquet'), ('colis', 'colis')], max_length=10, verbose_name="Unité d'utilisation")),
                ('net_weight_kg', models.DecimalField(decimal_places=4, default=1, help_text="Poids net en kg d'une unité d'achat", max_digits=8, verbose_name='Poids net (kg/unité)')),
                ('net_volume_l', models.DecimalField(decimal_places=4, default=1, help_text="Volume net en litre d'une unité d'achat", max_digits=8, verbose_name='Volume net (l/unité)')),
                ('pieces_per_package', models.DecimalField(decimal_places=0, default=1, max_digits=6, verbose_name='Pièces / paquet')),
                ('packages_per_purchase_unit', models.DecimalField(decimal_places=0, default=1, max_digits=6, verbose_name="Paquets / unité d'achat")),
                ('yield_rate', models.DecimalField(decimal_places=3, default=1, help_text='Ex: 0.85 pour 85% de matière utilisable après parage', max_digits=4, verbose_name='Rendement')),
                ('reference_price', models.DecimalField(decimal_places=4, default=0, help_text='Mis à jour automatiquement à chaque réception', max_digits=9, verbose_name='Prix de référence (HT)')),
                ('energy_kj', models.FloatField(blank=True, null=True, verbose_name='Énergie (kJ/100g)')),
                ('energy_kcal', models.FloatField(blank=True, null=True, verbose_name='Énergie (kcal/100g)')),
                ('fat', models.FloatField(blank=True, null=True, verbose_name='Lipides (g/100g)')),
                ('saturates', models.FloatField(blank=True, null=True, verbose_name='Dont saturés (g/100g)')),
                ('carbohydrates', models.FloatField(blank=True, null=True, verbose_name='Glucides (g/100g)')),
                ('sugars', models.FloatField(blank=True, null=True, verbose_name='Dont sucres (g/100g)')),
                ('protein', models.FloatField(blank=True, null=True, verbose_name='Protéines (g/100g)')),
                ('salt', models.FloatField(blank=True, null=True, verbose_name='Sel (g/100g)')),
                ('fiber', models.FloatField(blank=True, null=True, verbose_name='Fibres (g/100g)')),
                ('is_organic', models.BooleanField(default=False, verbose_name='Bio')),
                ('is_vegan', models.BooleanField(default=False, verbose_name='Végan')),
                ('is_veggie', models.BooleanField(default=False, verbose_name='Végétarien')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('allergens', models.ManyToManyField(blank=True, to='utilities.allergen', verbose_name='Allergènes')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='tenants.tenant')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.ingredientcategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Ingrédient',
                'verbose_name_plural': 'Ingrédients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nom')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_categories', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Catégorie de recette',
                'verbose_name_plural': 'Catégories de recettes',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Mode opératoire')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='recipes/', verbose_name='Photo')),
                ('yield_rate', models.DecimalField(decimal_places=3, default=1, help_text='Ex: 0.95 pour 95% de matière après cuisson', max_digits=4, verbose_name='Rendement')),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('litre', 'litre'), ('pièce', 'pièce')], default='pièce', max_length=6, verbose_name='Unité')),
                ('number_of_servings', models.PositiveIntegerField(default=1, verbose_name='Nombre de parts')),
                ('shelf_life_days', models.PositiveSmallIntegerField(default=0, verbose_name='DLC (jours)')),
                ('shelf_life_after_opening_days', models.PositiveSmallIntegerField(default=0, verbose_name='DLC après ouverture (jours)')),
                ('is_sellable', models.BooleanField(default=False, help_text='Cette recette peut être vendue telle quelle', verbose_name='Vendable')),
                ('selling_price_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix de vente TTC')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='tenants.tenant')),
                ('vat_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='utilities.vatrate', verbose_name='Taux de TVA')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.recipecategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Recette',
                'verbose_name_plural': 'Recettes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Quantité')),
                ('unit', models.CharField(max_length=10, verbose_name='Unité')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Note')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.ingredient', verbose_name='Ingrédient brut')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='catalog.recipe')),
                ('sub_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='catalog.recipe', verbose_name='Sous-recette')),
            ],
            options={
                'verbose_name': 'Ligne de recette',
                'verbose_name_plural': 'Lignes de recette',
            },
        ),
        migrations.AddConstraint(
            model_name='ingredientcategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_ingredient_category_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_ingredient_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='recipecategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_recipe_category_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_recipe_per_tenant'),
        ),
    ]
