# Generated by Django 5.2 on 2026-02-24 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='target_cooking_temp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ex: 70°C pour le poulet rôti', max_digits=5, null=True, verbose_name='T° cible de cuisson (°C)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='target_keeping_temp_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ex: 0°C min / 2°C max pour viande hachée', max_digits=5, null=True, verbose_name='T° conservation maximale (°C)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='target_keeping_temp_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='T° conservation minimale (°C)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='target_cooking_temp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Définie par article — utilisée dans CookingLog', max_digits=5, null=True, verbose_name='T° cible de cuisson (°C)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/', verbose_name='Photo du plat'),
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Ordre')),
                ('title', models.CharField(max_length=100, verbose_name="Titre de l'étape")),
                ('description', models.TextField(verbose_name='Description')),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Durée estimée (min)')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='catalog.recipe')),
            ],
            options={
                'verbose_name': 'Étape de recette',
                'verbose_name_plural': 'Étapes de recette',
                'ordering': ['recipe', 'order'],
            },
        ),
        migrations.CreateModel(
            name='RecipeStepPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='recipe_steps/', verbose_name='Photo')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Ordre')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalog.recipestep')),
            ],
            options={
                'verbose_name': "Photo d'étape",
                'verbose_name_plural': "Photos d'étapes",
                'ordering': ['step', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='recipestep',
            constraint=models.UniqueConstraint(fields=('recipe', 'order'), name='unique_step_order_per_recipe'),
        ),
    ]
