# Generated by Django 5.2 on 2026-02-24 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_ingredient_target_cooking_temp_and_more'),
        ('company', '0002_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_size', models.DecimalField(decimal_places=3, help_text='Quantité produite par cycle sur cet équipement', max_digits=8, verbose_name='Taille de lot')),
                ('batch_unit', models.CharField(max_length=10, verbose_name='Unité')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Notes')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.equipment', verbose_name='Équipement')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_lines', to='catalog.recipe')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_lines', to='catalog.recipestep', verbose_name='Étape associée')),
            ],
            options={
                'verbose_name': 'Équipement de recette',
                'verbose_name_plural': 'Équipements de recette',
                'ordering': ['recipe', 'step__order'],
            },
        ),
    ]
