# Generated by Django 5.2 on 2026-02-24 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_recipeequipment'),
        ('ciqual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='ciqual_ref',
            field=models.ForeignKey(blank=True, help_text='Lien vers la base ANSES — source des valeurs nutritionnelles', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ciqual.ciqualingredient', verbose_name='Référence CIQUAL'),
        ),
    ]
