# Generated by Django 5.2 on 2026-02-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_ingredient_ciqual_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='label_photo',
            field=models.ImageField(blank=True, help_text="Photo de l'étiquette pour lecture OCR", null=True, upload_to='ingredients/labels/', verbose_name='Photo étiquette'),
        ),
    ]
