# Generated by Django 5.2 on 2026-02-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_ingredient_label_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='yield_rate',
            field=models.DecimalField(decimal_places=3, default=1, help_text='Ex: 85 pour 85% de matière utilisable après parage', max_digits=6, verbose_name='Rendement'),
        ),
    ]
