# Generated by Django 5.2 on 2026-02-27 10:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_ingredient_yield_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipecategory',
            options={'ordering': ['name'], 'verbose_name': 'Catégorie de recette', 'verbose_name_plural': 'Catégories de recettes'},
        ),
        migrations.AlterModelOptions(
            name='recipeline',
            options={'ordering': ['order'], 'verbose_name': 'Ligne de recette', 'verbose_name_plural': 'Lignes de recette'},
        ),
        migrations.AlterModelOptions(
            name='recipestep',
            options={'ordering': ['order'], 'verbose_name': 'Étape de recette', 'verbose_name_plural': 'Étapes de recette'},
        ),
        migrations.RemoveConstraint(
            model_name='recipestep',
            name='unique_step_order_per_recipe',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='description',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='number_of_servings',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='target_cooking_temp',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='yield_rate',
        ),
        migrations.RemoveField(
            model_name='recipeline',
            name='note',
        ),
        migrations.AddField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes / conseils'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='output_quantity',
            field=models.DecimalField(decimal_places=4, default=1, help_text='Ex: 1 cadre 60x40, 12 portions, 2.5 kg', max_digits=10, verbose_name='Quantité produite'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='output_unit',
            field=models.CharField(choices=[('kg', 'kg'), ('litre', 'litre'), ('pièce', 'pièce'), ('portion', 'portion'), ('cadre', 'cadre'), ('plaque', 'plaque')], default='pièce', max_length=10, verbose_name='Unité de production'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='output_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Poids réel après cuisson/assemblage — sert au calcul nutritionnel', max_digits=10, null=True, verbose_name='Poids total produit (kg)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/photos/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(choices=[('recipe', 'Recette simple'), ('sub_recipe', 'Sous-recette / semi-fini'), ('product', 'Produit fini')], default='recipe', max_length=20, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='selling_price_ht',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Rempli uniquement si vendable tel quel', max_digits=9, null=True, verbose_name='Prix de vente HT'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recipeline',
            name='notes',
            field=models.CharField(blank=True, help_text='Ex: tamiser avant, température ambiante, haché finement...', max_length=200, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='recipeline',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AddField(
            model_name='recipestep',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/steps/', verbose_name="Photo de l'étape"),
        ),
        migrations.AddField(
            model_name='recipestep',
            name='temperature_c',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Ex: 180 pour un four, 4 pour une cellule de refroidissement', max_digits=5, null=True, verbose_name='Température (°C)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_sellable',
            field=models.BooleanField(default=False, help_text='Cochez si cette recette peut être vendue directement (ex: ketchup maison, mousse au chocolat)', verbose_name='Vendable tel quel'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='recipecategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='recipeline',
            name='ingredient',
            field=models.ForeignKey(blank=True, help_text="Laisser vide si c'est une sous-recette", null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.ingredient', verbose_name='Ingrédient'),
        ),
        migrations.AlterField(
            model_name='recipeline',
            name='sub_recipe',
            field=models.ForeignKey(blank=True, help_text="Laisser vide si c'est un ingrédient brut", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_in_lines', to='catalog.recipe', verbose_name='Sous-recette'),
        ),
        migrations.AlterField(
            model_name='recipeline',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('litre', 'litre'), ('ml', 'ml'), ('pièce', 'pièce'), ('portion', 'portion'), ('cs', 'c. à soupe'), ('cc', 'c. à café'), ('pincée', 'pincée')], max_length=10, verbose_name='Unité'),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description détaillée'),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Durée (min)'),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='title',
            field=models.CharField(max_length=200, verbose_name="Titre de l'étape"),
        ),
        migrations.AddConstraint(
            model_name='recipeline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ingredient__isnull', False), ('sub_recipe__isnull', True)), models.Q(('ingredient__isnull', True), ('sub_recipe__isnull', False)), _connector='OR'), name='recipeline_ingredient_xor_subrecipe', violation_error_message='Une ligne doit avoir soit un ingrédient, soit une sous-recette — pas les deux, pas aucun.'),
        ),
    ]
