# Generated by Django 5.2 on 2026-02-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_recipecategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='density_kg_per_l',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="Masse d'un litre du produit. Ex: huile=0.8, eau=1.0, miel=1.4. Laisser vide si non applicable (produits solides achetés au kg).", max_digits=5, null=True, verbose_name='Densité (kg/l)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='net_volume_l',
            field=models.DecimalField(decimal_places=4, default=1, help_text="Volume net total de l'unité d'achat complète (litres). Ex: colis 6×75cl → 4.5 l. Laisser à 1 si non applicable.", max_digits=8, verbose_name='Volume net (l/unité)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='net_weight_kg',
            field=models.DecimalField(decimal_places=4, default=1, help_text="Poids net total de l'unité d'achat complète (kg). Ex: colis 6×75cl d'huile → 3.6 kg. Sac farine 25kg → 25.", max_digits=8, verbose_name='Poids net (kg/unité)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='reference_price',
            field=models.DecimalField(decimal_places=4, default=0, help_text="Saisir les prix dans l'onglet Prix de la fiche ingrédient.", max_digits=9, verbose_name='Prix de référence (HT)'),
        ),
    ]
