# Generated by Django 5.2 on 2026-02-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_ingredient_density_kg_per_l_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='bio_percent',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='% ingrédients bio (calculé)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='composition_data',
            field=models.JSONField(blank=True, default=dict, help_text='Généré automatiquement — liste récursive de tous les ingrédients', verbose_name='Composition complète (JSON)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cost_total_cached',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Mis à jour automatiquement via signal post_save', max_digits=10, verbose_name='Coût total (caché)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_vegan_computed',
            field=models.BooleanField(default=False, verbose_name='Végan (calculé)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_veggie_computed',
            field=models.BooleanField(default=False, verbose_name='Végétarien (calculé)'),
        ),
    ]
