# Generated by Django 5.2 on 2026-03-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_recipe_bio_percent_recipe_composition_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeline',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('litre', 'litre'), ('cl', 'cl'), ('ml', 'ml'), ('pièce', 'pièce'), ('portion', 'portion'), ('cs', 'cuillère à soupe'), ('cc', 'cuillère à café'), ('pincée', 'pincée'), ('cadre', 'cadre'), ('plaque', 'plaque')], max_length=10, verbose_name='Unité'),
        ),
    ]
