# Generated by Django 5.2 on 2026-03-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_recipeline_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='yield_rate',
            field=models.DecimalField(decimal_places=4, default=1, help_text='Ex: 0.90 pour 90% de matière utilisable', max_digits=5, verbose_name='Rendement'),
        ),
    ]
